# Generated by Django 4.2.4 on 2023-08-24 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_name', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('reg_no', models.IntegerField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('Degree', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.course')),
            ],
        ),
    ]
