# Generated by Django 4.2.4 on 2023-08-29 12:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0002_student_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Student_image_NEW',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='student_images_NEW'),
        ),
    ]
